import { Jeux } from "./Jeux"
export const JEUX: Jeux[] =[

   
            {"id":1,
            "titre":"Dragon's Dogma 2",
            "platform":["pc","ps5","xbox"],
            "description":"Remarque : cet objet est inclus dans d'autres sets.\n\nPréparez-vous pour votre grande aventure, Insurgé !\n\nDragon's Dogma est un RPG action en solo à l'histoire riche, qui invite les joueurs à définir leur propre expérience, de l'apparence de leur Insurgé, à leur classe, leur groupe, la façon dont ils approchent les différentes situations, et plus encore. Avec cette suite tant attendue, le vaste monde de fantasy à explorer de Dragon's Dogma 2 vous tend désormais les bras.\n\nAu cours de votre voyage, des pions se joindront à vous. Ces mystérieux êtres surnaturels vous donneront l'impression d'être accompagné d'autres joueurs en chair et en os tout au long de cette aventure unique.\n\nL'expérience sera encore sublimée davantage par les systèmes physiques, l'intelligence artificielle (IA) et les graphismes à la pointe du progrès, qui donnent vie au monde de fantasy ensorcelant de Dragon's Dogma 2.\n\nDe l'action qui met votre créativité à l'épreuve\n\nFrappez à l'épée, tirez à l'arc et utilisez la magie.\nLes Classes de Dragon's Dogma 2 vous permettent d'aborder le combat comme vous l'entendez.",
            "sortie":"22 mars 2024",
            "image":["./assets/Dragon_Dogma2.jpg","./assets/Dragon_Dogma2-2.jpg","./assets/Dragon_Dogma2-3.jpg"],
            "video":"",
            "prix":"43.25€",
            "Promo":"",
            "genre":["jeux solo","action","aventure","RPG"]},
            {"id":2,
            "titre":"Helldivers 2",
            "platform":["pc","ps5"],
            "description":"Acheter HELLDIVERS 2 en clé Steam chez Gamesplanet.com\n\n        La dernière ligne d'attaque de la galaxie.\n        \n        Engagez-vous chez les Helldivers et rejoignez le combat pour la liberté à travers une galaxie hostile dans ce jeu de tir à la troisième personne frénétique et féroce.\n        \n        DIFFUSION URGENTE – FORCES ARMÉES DE LA SUPER-TERRE\n        Liberté. Paix. Démocratie. Vos droits inaliénables en tant qu'enfant de la Super-Terre. Les piliers de notre civilisation.\n        De notre existence même.\n        Mais la guerre fait rage. Et tout est à nouveau menacé.\n        Rejoignez la meilleure armée de la galaxie et rendez sa liberté et sa sécurité à votre foyer.\n        \n        DEVENEZ UNE LÉGENDE\n        Vous serez rassemblés en escouades de quatre Helldivers maximum et des missions stratégiques vous seront assignées.Protégez-vous les uns les autres ; le tir allié est inévitable, mais la victoire sans travail d'équipe est impossible.\n        \n        ÉQUIPEMENT\n        Faites pleuvoir la liberté depuis les cieux, infiltrez-vous en territoire ennemi, ou serrez les dents et foncez tête la première dans le feu du combat.Votre manière d'administrer la liberté dépend de vous ; vous aurez accès à un vaste choix d'armes à feu explosives, d'armures robustes et de stratagèmes décisifs... le joyau de l'arsenal de tout Helldiver qui se respecte.\n        \n        RÉQUISITION\n        La Super-Terre reconnaît votre investissement et vous octroie des réquisitions. Utilisez-les pour accéder à différentes récompenses pour vous, votre escouade, votre destroyer et l'effort de guerre général.",
            "sortie":"8 février 2024",
            "image":["./assets/Hell_Divers2.jpg","./assets/Hell_Divers2-1.jpg","./assets/Hell_Divers2-2.jpg"],
            "video":"",
            "prix":"29.99€",
            "Promo":"",
            "genre":["Co-op en ligne","aventure"]},
            {"id":3,
            "titre":"Dying Light 2 Stay Human Reloaded Edition",
            "platform":["pc","ps5","xbox"],
            "description":"Vingt ans se sont écoulés depuis les événements du jeu original. Le virus a gagné du terrain et l'humanité se meurt lentement. Vous incarnez Aiden Caldwell, un pèlerin errant qui livre des marchandises, apporte des nouvelles et relie les quelques colonies de survivants restantes dans des terres arides dévastées par le virus zombie. Cependant, votre véritable objectif est de retrouver votre petite sœur Mia, que vous avez laissée derrière vous lorsque vous étiez enfant pour échapper aux expériences de torture du Dr Waltz. Hanté par votre passé, vous décidez finalement de l'affronter lorsque vous apprenez que Mia est peut-être encore en vie à Villedor, la dernière ville encore debout sur Terre.\n\nVous vous retrouvez rapidement dans un village déchiré par les conflits. Vous devrez vous engager dans des combats inventifs et sanglants et affiner vos compétences pour vaincre les hordes de zombies et vous faire des alliés. Parcourez la ville, courez librement à travers les bâtiments et par dessus les toits de Villedor à la recherche de butin dans les zones reculées, mais méfiez-vous de la nuit car à chaque coucher de soleil, des monstres prennent le contrôle des rues.",
            "sortie":"22 février 2024",
            "image":["./assets/Dying Light 2.jpg","./assets/Dying light 2-1.jpg","./assets/Dying light 2-2.jpg"],
            "video":"",
            "prix":"19.99€",
            "Promo":"",
            "genre":["jeux solo","action","aventure","RPG"]},
            {"id":4,
            "titre":"Ghost of Tsushima: Director's Cut",
            "platform":["pc","ps5"],
            "description":"Vingt ans se sont écoulés depuis les événements du jeu original. Le virus a gagné du terrain et l'humanité se meurt lentement. Vous incarnez Aiden Caldwell, un pèlerin errant qui livre des marchandises, apporte des nouvelles et relie les quelques colonies de survivants restantes dans des terres arides dévastées par le virus zombie. Cependant, votre véritable objectif est de retrouver votre petite sœur Mia, que vous avez laissée derrière vous lorsque vous étiez enfant pour échapper aux expériences de torture du Dr Waltz. Hanté par votre passé, vous décidez finalement de l'affronter lorsque vous apprenez que Mia est peut-être encore en vie à Villedor, la dernière ville encore debout sur Terre.\n\nVous vous retrouvez rapidement dans un village déchiré par les conflits. Vous devrez vous engager dans des combats inventifs et sanglants et affiner vos compétences pour vaincre les hordes de zombies et vous faire des alliés. Parcourez la ville, courez librement à travers les bâtiments et par dessus les toits de Villedor à la recherche de butin dans les zones reculées, mais méfiez-vous de la nuit car à chaque coucher de soleil, des monstres prennent le contrôle des rues.",
            "sortie":"17 juillet 2020",
            "image":["./assets/Ghost of tsushima.jpg","./assets/Ghost of tsushima-1.jpg","./assets/Ghost of tsushima-2.jpg"],
            "video":"",
            "prix":"45.00€",
            "Promo":"",
            "genre":["jeux solo","action","aventure"]},
            {"id":5,
            "titre":"Grand Theft Auto V: Premium Online Edition",
            "platform":["pc","ps5","xbox"],
            "description":"Grand Theft Auto V : Édition Premium inclut l'histoire complète de Grand Theft Auto V, un accès gratuit au monde en perpétuelle évolution de Grand Theft Auto Online et aux améliorations de gameplay et au contenu existants, dont le Braquage de Cayo Perico, le Diamond Casino & Hôtel, le Braquage du Diamond Casino, Trafic d'armes, et bien plus encore. Vous obtiendrez également le Pack d'entrée dans le monde criminel, le moyen le plus rapide de lancer votre empire criminel dans Grand Theft Auto Online.\n\n        GRAND THEFT AUTO V\n        Un jeune arnaqueur, un braqueur de banque à la retraite et un terrible psychopathe doivent effectuer une série de braquages pour survivre dans une ville sans pitié où ils ne peuvent faire confiance à personne, et encore moins à leurs compagnons.\n        \n        GRAND THEFT AUTO ONLINE\n        Découvrez un monde en constante évolution où vous pourrez gravir les échelons de la hiérarchie criminelle de Los Santos et de Blaine County comme vous le souhaitez dans l'expérience en ligne ultime.\n        \n        LE PACK D'ENTRÉE DANS LE MONDE CRIMINEL\n        Le Pack d'entrée dans le monde criminel est pour les nouveaux joueurs de GTA Online le moyen le plus rapide de lancer leur empire criminel. Profitez du contenu le plus populaire et d'un bonus de 1 000 000 GTA$ à dépenser en jeu, le tout pour une valeur totale de plus de 10 000 000 GTA$ (si acheté séparément).",
            "sortie":"14 avril 2015",
            "image":["./assets/GTA5.jpg","./assets/GTA5-1.jpg","./assets/GTA5-2.jpg"],
            "video":"",
            "prix":"10.49€",
            "Promo":"",
            "genre":["jeux solo","action","aventure","multijoueur"]},
            {"id":6,
            "titre":"Minecraft: Java & Bedrock Edition",
            "platform":["pc","ps5","xbox"],
            "description":"Minecraft: Java + Bedrock Edition\n\n        Minecraft pour PC est le jeu vidéo le plus vendu de tous les temps. Rien que cela devrait suffire à vous convaincre, mais voici un peu plus d'informations sur les raisons pour lesquelles vous devriez commencer à jouer dès maintenant. C'est un jeu de bac à sable (sandbox) dans lequel les joueurs doivent extraire, construire et fabriquer pour créer leur monde idéal et on peut voir des réalisations fascinantes !",
            "sortie":"14 avril 2015",
            "image":["./assets/Minecraft.jpg","./assets/Minecraft-1.jpg","./assets/Minecraft-2.jpg"],
            "video":"",
            "prix":"18.67€",
            "Promo":"",
            "genre":["gestion","multijoueur","RPG"]},
            {"id":7,
            "titre":"Dead Space",
            "platform":["pc","ps5","xbox"],
            "description":"Dead Space, le classique du genre « survival horror » de science-fiction, fait son grand retour. Le jeu a été complètement recréé pour vous offrir une expérience plus réaliste et immersive. Entre le rendu des graphismes spectaculaire, l'ambiance sonore pleine de suspense et les améliorations des mécaniques de jeu, ce remake sublime l’expérience tout en restant fidèle à la vision captivante du jeu original.\n\n        Isaac Clarke est un ingénieur ordinaire en mission pour réparer l’USG Ishimura, un gigantesque vaisseau minier. Une fois à bord, il fait une découverte macabre : tout l’équipage a été massacré et Nicole, sa petite amie, a disparu dans les tréfonds du vaisseau.\n        \n        Seul à faire face à ce cauchemar, avec pour seules armes ses outils et ses compétences d'ingénieur, Isaac est plus que jamais déterminé à retrouver Nicole. Le mystère plane autour des événements qui ont eu lieu à bord de l’Ishimura et Isaac compte bien découvrir la vérité sur ces derniers. Pris au piège avec des créatures hostiles appelées Nécromorphes, Isaac doit lutter pour sa survie ; non seulement contre les menaces croissantes du vaisseau mais également pour préserver sa santé mentale face aux horreurs qu'il va vivre. ",
            "sortie":"27 janvier 2023",
            "image":["./assets/Dead space.jpg","./assets/Dead space-1.jpg","./assets/Dead space-2.jpg"],
            "video":"",
            "prix":"22.98€",
            "Promo":"",
            "genre":["jeux solo","action","aventure"]},
            {"id":8,
            "titre":"Dark Souls 3",
            "platform":["pc","ps5","xbox"],
            "description":"Dark Souls 3 pour PC est un jeu de rôle d'action fantastique, le quatrième de la série, qui fait suite à son prédécesseur immédiat, Dark Souls 2. Le jeu se déroule dans un univers fictif, dans le Royaume de Lothric, où la longue période d'illumination (littéralement) est menacée par la venue de l'Age des Ténèbres. Le joueur doit s'assurer de survivre à l'Âge de Feu en s'assurant que la Première Flamme continue à brûler un peu plus longtemps. ",
            "sortie":"11 avril 2016",
            "image":["./assets/Dark soul 3.jpg","./assets/Dark soul 3-1.jpg","./assets/Dark soul 3-2.jpg"],
            "video":"",
            "prix":"19.65€",
            "Promo":"",
            "genre":["jeux solo","action"]},
            {"id":9,
            "titre":"Tekken 8",
            "platform":["pc","ps5","xbox"],
            "description":"Armed with jaw-dropping HD graphics running flawlessly at 60 fps; the largest character roster ever in Tekken history; ground-breaking competitive online modes and robust character customization system, the greatest fighting game franchise soars onto the Xbox computer entertainment system!",
            "sortie":"26 janvier 2024",
            "image":["./assets/Tekken 8.jpg","./assets/Tekken 8-1.jpg","./assets/Tekken 8-2.jpg"],
            "video":"",
            "prix":"47.99€","Promo":"",
            "genre":["jeux solo","action"]},
            {"id":10,
            "titre":"Path of Exile",
            "platform":["pc"],
            "description":"Path of Exile est un jeu de rôle d'action (ARPG), très inspiré de Diablo on parle ici de Diablo like dans lequel le joueur choisit l'une des sept classes de personnages à incarner. Voir ci-dessous pour en savoir plus sur les classes de personnages.\n\nLe jeu se déroule dans un monde fantastique dystopique dans lequel les personnages sont exilés de la nation insulaire d'Oriath vers le continent de Wraeclast, un continent aujourd'hui détruit. Le continent était autrefois un centre d'empire fabuleux et civilisé, mais il abrite désormais des prisonniers et des criminels. Il est aussi, comme vous le découvrirez bientôt, la demeure de nombreux dieux anciens.\n\nVotre tâche consiste à vous frayer un chemin jusqu'à Oriath, en vainquant ces dieux et d'autres grands maux en cours de route. Vous devrez découvrir des vestiges de l'Empire éternel, autrefois puissant, et même des signes de la civilisation Vaal. Faites équipe avec d'autres exilés pour éviter de tomber dans les griffes des bandits assoiffés de sang qui envahissent le continent, alors que vous luttez à travers les terres désolées dans votre effort pour rentrer chez vous.\n\nVous devez défendre les autres exilés contre les brutes et les monstres, accepter les quêtes et les missions des PNJ et découvrir les secrets qui se cachent derrière les horreurs de Wraeclast. Vous vous rendrez vite compte qu'une fois les antagonistes de Wraeclast éliminés, le jeu ne fait en fait que commencer à se réchauffer !\n\nVous retournez en triomphe à Oriath, pour découvrir qu'il y a encore plus de brutes et de monstres à vaincre, même s'ils se font passer pour des dirigeants bons et honnêtes - il y a donc un travail de détective à faire aussi, pour découvrir qui n'a pas les intentions aussi pures qu'il le prétend.",
            "sortie":"23 octobre 2013",
            "image":["./assets/path-of-exile-1.jpg","./assets/path-of-exile-2.jpg","./assets/path-of-exile-3.jpg"],
            "video":"",
            "prix":"Free to play",
            "Promo":"",
            "genre":["aventure","action","free to play","RPG","jeux solo","MMO","multijoueur","Co-op en ligne"]},
            
            {"id":11,
            "titre":"Cyberpunk 2077: Ultimate Edition",
            "platform":["pc","ps5","xbox"],
            "description":"Cyberpunk 2077 est un RPG d'action-aventure en monde ouvert qui se déroule dans la mégalopole de Night City, où vous incarnez un cyber-mercenaire qui livre un combat sans merci pour sa survie. Avec des améliorations et du contenu additionnel gratuit, personnalisez entièrement votre personnage et votre style de jeu en accomplissant des boulots, améliorez votre réputation et déverrouillez des améliorations. Les relations que vous nouerez et les choix que vous ferez auront un impact sur l'histoire et le monde qui vous entoure. C'est ici que se forgent les légendes. Quelle sera la vôtre ?\n\nNight City semble plus vivante que jamais grâce à la mise à jour 2.1 entièrement gratuite ! Voyagez sur le réseau de métro NCART parfaitement fonctionnel, écoutez de la musique en explorant la ville avec le Radioport, passez du temps avec votre conquête chez V, participez à des courses rejouables, pilotez de nouveaux véhicules, profitez de la maniabilité améliorée des motos et des nouvelles possibilités de combat qu'elles offrent, découvrez des secrets cachés et bien plus encore !\n\nDevenez un hors-la-loi urbain équipé d'améliorations cybernétiques et forgez votre légende dans les rues de Night City.\n\nNight City regorge de choses à faire, d'endroits à voir et de gens à rencontrer. Et vous êtes libre d'aller où vous voulez, quand vous voulez, comme vous voulez.\n\nLancez-vous dans des aventures risquées et nouez des relations avec des personnages inoubliables dont le sort dépendra de vos choix.\n\nRedécouvrez Cyberpunk 2077 avec de nombreux changements et améliorations apportés au gameplay, à l'économie, à l'ergonomie de la carte et bien plus.\n\nObtenez des cadeaux en jeu et des goodies numériques inspirés des jeux CD PROJEKT RED dans le cadre du programme Mes Récompenses.",
            "sortie":"5 décembre 2023",
            "image":["./assets/cyberpunk-2077-1.jpg","./assets/cyberpunk-2077-2.jpg","./assets/cyberpunk-2077-3.jpg"],
            "video":"",
            "prix":"37.16€",
            "Promo":"",
            "genre":["jeux solo","RPG"]},
            {"id":12,
            "titre":"Fallout 4 GOTY Edition",
            "platform":["pc","xbox"],
            "description":"Bethesda Game Studios, studio de développement maintes fois récompensé à l'origine de Fallout 3 et de The Elder Scrolls V: Skyrim, vous invite à découvrir Fallout 4, leur titre le plus ambitieux à ce jour incarnant la nouvelle génération du jeu en monde ouvert.\n\nDans la peau du seul survivant de l'abri 111, vous émergez dans un monde dévasté par une guerre nucléaire. Votre survie sera un combat de tous les instants et vos choix façonneront votre destin. Vous seul avez le pouvoir de faire entrer les Terres désolées dans une nouvelle ère. Bienvenue chez vous.\n\nJouissez d'une liberté d'action sans précédent dans un monde ouvert offrant des centaines de lieux, de personnages et de quêtes. Rejoignez plusieurs factions dans leur combat pour la suprématie ou forgez votre destinée en loup solitaire, c'est à vous seul de décider.\n\nNIncarnez le personnage que vous voulez grâce au système S.P.E.C.I.A.L. Soldat en armure assistée ou baratineur charismatique, choisissez parmi des centaines d'aptitudes et développez votre propre style de jeu.\n\nUn tout nouveau moteur graphique et une gestion des éclairages de nouvelle génération donnent vie au monde de Fallout comme jamais auparavant. Des forêts dévastées du Commonwealth aux ruines de Boston, chaque lieu fourmille de détails dynamiques. \n\nLes combats intenses à la première ou à la troisième personne peuvent aussi être ralentis grâce au nouveau Système de Visée Assistée Vault-Tec (SVAV) dynamique, qui vous permet de choisir vos attaques avant de profiter du carnage comme si vous y étiez.\n\nTrouvez, améliorez et créez des milliers d'objets grâce au système de fabrication le plus sophistiqué jamais conçu. Armes, armures, substances chimiques et nourriture ne sont qu'une infime partie des possibilités : vous pourrez même construire et gérer des colonies entières !",
            "sortie":"10 novembre 2015",
            "image":["./assets/fallout-4-goty-1.jpg","./assets/fallout-4-goty-2.jpg","./assets/fallout-4-goty-3.jpg"],
            "video":"",
            "prix":"7.49€",
            "Promo":"",
            "genre":["jeux solo","RPG"]},
            {"id":13,
            "titre":"Horizon Forbidden West Complete Edition",
            "platform":["pc","ps5"],
            "description":"Accompagnez Aloy dans son périple au cœur d'un territoire majestueux mais non moins périlleux, qui abrite de mystérieuses nouvelles menaces. Avec la version Complete Edition, profitez du jeu à succès Horizon Forbidden West sur PC ainsi que de contenu bonus, y compris l'extension Burning Shores dont l'histoire commence directement après le jeu principal.\n\nExplorez des terres lointaines, affrontez des machines toujours plus imposantes et dévastatrices, et rencontrez de nouvelles tribus fascinantes lors de votre retour dans le monde d'Horizon dépeignant un futur lointain post-apocalyptique.\n\nLe monde se meurt. De terribles tempêtes et un déclin inéluctable s'abattent sur les vestiges épars de l'humanité, tandis que de nouvelles machines effrayantes rôdent aux frontières et que la vie sur Terre se précipite vers une nouvelle extinction.\n\nC'est à Aloy que revient la mission de découvrir les secrets de ces menaces et de restaurer l'ordre et l'équilibre du monde. Dans sa quête, elle devra retrouver d'anciens amis, forger des alliances avec de nouvelles factions guerrières et exhumer les secrets des temps anciens.\n\nObservez chaque détail du jeu avec les formats d'image Ultrawide 21:9 et Super Ultrawide 32:9, ainsi que la prise en charge du triple écran 48:9.*\n\nRegardez l'Ouest prohibé prendre vie grâce au rendu optimisé et à la génération d'images NVIDIA DLSS 3, à l'amélioration d'images NVIDIA DLAA et à la réduction de latence NVIDIA Reflex. AMD FSR et Intel XeSS sont également compatibles.",
            "sortie":"21 mars 2024",
            "image":["./assets/horizon-forbidden-1.jpg","./assets/horizon-forbidden-2.jpg","./assets/horizon-forbidden-3.jpg"],
            "video":"",
            "prix":"44.10€",
            "Promo":"",
            "genre":["jeux solo","action","RPG"]},
            {"id":14,
            "titre":"Elden Ring Shadow Of The Erdtree",
            "platform":["pc","ps5"],
            "description":"UNE NOUVELLE AVENTURE GRANDIOSE VOUS ATTEND Levez-vous, Sans-éclat, et puisse la grâce guider vos pas. Brandissez la puissance du Cercle d'Elden. Devenez Seigneur de l'Entre-terre.• Un vaste monde à explorerUn monde immense aux environnements riches et variés, parsemé d'obscurs et tortueux donjons tous reliés naturellement entre eux, vous attend. Au fil de votre exploration, goûtez à l'inconnu, bravez les menaces permanentes et accomplissez votre destinée",
            "sortie":"24 juin 2024",
            "image":["./assets/elden-ring-shadow-of-the-erdtree-edition-shadow-of-the-erdtree-edition-pc-spiel-steam-europe-cover.jpg","./assets/elden-ring-shadow-of-the-erdtree-edition-shadow-of-the-erdtree-edition-pc-spiel-steam-europe-wallpaper-1-big.jpg","./assets/elden-ring-shadow-of-the-erdtree-edition-shadow-of-the-erdtree-edition-pc-spiel-steam-europe-wallpaper-4-thumbv2.jpg"],
            "video": "./assets/elden-ring-shadow-of-the-erdtree-edition-shadow-of-the-erdtree-edition-pc-spiel-steam-europe-preview.webm",
            "prix":"61.49€", 
            "Promo":"-23%"  ,        
            "genre":["jeux solo","action","RPG"]},
            {"id":15,
            "titre":"Moto GP24",
            "platform":["pc","ps5","xbox"],
            "description":"Testez vos aptitudes de pilote avec MotoGP™, Moto2™ et Moto3™, et découvrez sans plus attendre l’incroyable campagne 2024. Vivez l’expérience MotoGP™24 à fond avec la liste complète des pilotes et les circuits officiels !UNE CARRIÈRE IMPRÉVISIBLEEnfilez votre blouson de pilote pour devenir l’une des légendes de MotoGP™ et créer votre propre saga mémorable",
            "sortie":"02 mai 2024",
            "image":["./assets/motogp-24-pc-jeu-steam-wallpaper-1-big.jpg","./assets/motogp-24-pc-jeu-steam-wallpaper-2-thumbv2.jpg","./assets/motogp-24-pc-jeu-steam-wallpaper-5-thumbv2.jpg"],
            "video": "./assets/motogp-24-pc-jeu-steam-preview.webm",
            "prix":"37.99€", 
            "Promo":"-24%"  ,        
            "genre":["jeux solo","sport",]},
            {"id":16,
            "titre":"TopSpin 2K25 Deluxe Edition ",
            "platform":["pc","ps5","xbox"],
            "description":"GAGNEZ LE GRAND CHELEM® EN CARRIÈRE[/u] Parcourez le monde, affrontez les plus grands noms du tennis et jouez sur le court central de Wimbledon, Roland-Garros, l'US Open et l'Open d'Australie pour devenir un champion du Grand chelem® dans MyCAREER.JOUEZ DANS DES LIEUX LÉGENDAIRES Rendez-vous sur les plus grands courts de tennis dans TopSpin 2K25",
            "sortie":"23 avril 2024",
            "image":["./assets/topspin-2k25-deluxe-edition-acces-anticipe-deluxe-edition-pc-jeu-steam-europe-wallpaper-1-big.jpg","./assets/topspin-2k25-deluxe-edition-acces-anticipe-deluxe-edition-pc-jeu-steam-europe-wallpaper-2-thumbv2.jpg","./assets/topspin-2k25-deluxe-edition-acces-anticipe-deluxe-edition-pc-jeu-steam-europe-wallpaper-5-thumbv2.jpg"],
            "video": "./assets/topspin-2k25-deluxe-edition-acces-anticipe-deluxe-edition-pc-jeu-steam-europe-preview.webm",
            "prix":"69.99€", 
            "Promo":"-30%"  ,        
            "genre":["jeux solo","sport",]},
            {"id":17,
            "titre":"S.T.A.L.K.E.R. 2: Heart of Chornobyl",
            "platform":["pc","ps5","xbox"],
            "description":"La Zone d'exclusion de Tchornobyl a changé de manière spectaculaire après la seconde explosion en 2006. Les mutants violents, les anomalies mortelles et les conflits entre ses nombreuses factions ont fait de la Zone un endroit où il est très difficile de survivre. Cependant, les artefacts d'une valeur incroyable qui s'y trouvent attirent de nombreuses personnes, appelées les “Stalkers”, qui s'infiltrent dans la Zone à leurs risques et périls",
            "sortie":"05 septembre 2024",
            "image":["./assets/s-t-a-l-k-e-r-2-heart-of-chornobyl-ultimate-edition-ultimate-edition-pc-jeu-steam-europe-wallpaper-1-big.jpg","./assets/s-t-a-l-k-e-r-2-heart-of-chornobyl-ultimate-edition-ultimate-edition-pc-jeu-steam-europe-wallpaper-3-thumbv2.jpg","./assets/s-t-a-l-k-e-r-2-heart-of-chornobyl-ultimate-edition-ultimate-edition-pc-jeu-steam-europe-wallpaper-4-thumbv2.jpg"],
            "video": "./assets/s-t-a-l-k-e-r-2-heart-of-chornobyl-ultimate-edition-ultimate-edition-pc-jeu-steam-europe-preview.webm",
            "prix":"62.89€", 
            "Promo":"-43%"  ,        
            "genre":["jeux solo","fps","action"]},
            {"id":18,
            "titre":"Eiyuden Chronicle: Hundred Heroes",
            "platform":["pc",],
            "description":"Notre aventure commence dans une région d'Allraan, un continent aux cultures très diverses. C'est par l'épée et des objets magiques appelés des « lentilles runiques » que l'histoire de ces terres a été façonnée. Une histoire d'alliances et de guerres entre humains, elfes hommes-bêtes et habitants du désert. L’empire Galdéen a devancé les autres nations et a découvert une technologie qui amplifie la magie des lentilles runiques",
            "sortie":"23 avril 2024",
            "image":["./assets/eiyuden-chronicle-hundred-heroes-pc-jeu-steam-europe-wallpaper-1-big.jpg","./assets/eiyuden-chronicle-hundred-heroes-pc-jeu-steam-europe-wallpaper-2-thumbv2.jpg","./assets/eiyuden-chronicle-hundred-heroes-pc-jeu-steam-europe-wallpaper-3-thumbv2.jpg"],
            "video": "./assets/eiyuden-chronicle-hundred-heroes-pc-jeu-steam-europe-preview.webm",
            "prix":"32.89€", 
            "Promo":"-34%"  ,        
            "genre":["jeux solo","rpg","aventure"]},
            {"id":19,
            "titre":"Homeworld 3",
            "platform":["pc",],
            "description":"Achetez l'édition Fleet Command de Homeworld 3 aujourd'hui pour recevoir : Jeu de base Passe Premier Anniversaire de Homeworld 3 Bande-son de Homeworld 3 par Paul Ruskay Jouez 72 heures en avance Ensemble de personnalisation multijoueur Couleur du sillage de réacteur Couleur du nom multijoueur Bannières de profil Autocollants de vaisseau L'ensemble de personnalisation multijoueur contient des stickers de vaisseau, des bannières de profil...",
            "sortie":"12 mai 2024",
            "image":["./assets/homeworld-3-fleet-command-edition-acces-anticipe-fleet-command-edition-pc-jeu-steam-europe-cover.jpg","./assets/homeworld-3-fleet-command-edition-acces-anticipe-fleet-command-edition-pc-jeu-steam-europe-wallpaper-1-big.jpg","./assets/homeworld-3-fleet-command-edition-acces-anticipe-fleet-command-edition-pc-jeu-steam-europe-wallpaper-2-thumbv2.jpg"],
            "video": "./assets/homeworld-3-fleet-command-edition-acces-anticipe-fleet-command-edition-pc-jeu-steam-europe-preview.webm",
            "prix":"66.49€", 
            "Promo":"-26%"  ,        
            "genre":["jeux solo","rpg","aventure"]},
            {"id":20,
            "titre":"Crown Wars: The Black Prince",
            "platform":["pc","xbox","ps5"],
            "description":"La guerre des couronnes fait rage. Chevaliers, brigands et une mystérieuse force maléfique sèment la désolation dans tout le pays. A la tête de votre baronnie, menez le combat dans ce jeu tactique et stratégique au tour par tour. ...",
            "sortie":"23 mai 2024",
            "image":["./assets/crown-wars-the-black-prince-sacred-edition-sacred-edition-pc-jeu-steam-europe-cover.jpg","./assets/crown-wars-the-black-prince-sacred-edition-sacred-edition-pc-jeu-steam-europe-wallpaper-1-big.jpg","./assets/crown-wars-the-black-prince-sacred-edition-sacred-edition-pc-jeu-steam-europe-wallpaper-2-thumbv2.jpg"],
            "video": "./assets/crown-wars-the-black-prince-sacred-edition-sacred-edition-pc-jeu-steam-europe-preview.webm",
            "prix":"35.79€", 
            "Promo":"-28%"  ,        
            "genre":["jeux solo","aventure"]},
            {"id":21,
            "titre":"No Rest for the Wicked",
            "platform":["pc"],
            "description":"Moon Studios, les développeurs récompensés pour Ori and the Blind Forest et Ori and the Will of the Wisps, vous présentent No Rest for the Wicked, un jeu d'Action-RPG sanglant et exigeant pensé pour réinventer le genre.\n\nEn l'an 841, le roi Harol est mort. Tandis que la nouvelle de sa mort résonne dans tout le royaume, la couronne revient à son fils Magnus, un prince arrogant dont la valeur reste à prouver.\n\nPire encore, la Pestilence, une abominable peste éteinte depuis un millénaire, réapparaît. Elle souffle sur les terres en corrompant tout et tous ceux qu'elle touche. La Madrigale Seline, figure de l'église nourrissant une implacable ambition, voit en la Pestilence l'occasion de faire ses preuves aux yeux de son dieu.",
            "sortie":"18 avril 2024",
            "image":["./assets/no-rest-for-the-wicked-1.jpg","./assets/no-rest-for-the-wicked-2.jpg","./assets/no-rest-for-the-wicked-3.jpg"],
            "video":"",
            "prix":"28.65€",
            "Promo":"-28%",
            "genre":["jeux solo","action","aventure","RPG"]},
            {"id":22,
            "titre":"Achilles: Legends Untold",
            "platform":["pc"],
            "description":"Achilles: Legends Untold est un RPG d'action avec des mécaniques de combat de type souls-like, se déroulant dans le monde mythique de la Grèce antique, où vous incarnez le courageux guerrier Achille.\n\nPour une expérience de jeu optimale, nous vous recommandons d'utiliser une manette.\n\nPlongez dans un monde où maîtriser le combat, des tactiques de défense comme le blocage et l'esquive à une large gamme d'attaques, est la clé du succès.\n\nvous tombez au combat, relevez-vous, améliorez les compétences de votre héros, essayez une tactique différente et repartez à l'aventure.",
            "sortie":"2 novembre 2023",
            "image":["./assets/achilles-legends-untold-1.jpg","./assets/achilles-legends-untold-2.jpg","./assets/achilles-legends-untold-13.jpg"],
            "video":"",
            "prix":"9.37€",
            "Promo":"-59%",
            "genre":["jeux solo","action","RPG"]},
            {"id":23,
            "titre":"Call of Duty: Modern Warfare III",
            "platform":["pc","ps5","xbox"],
            "description":"Remarque : cet objet est inclus dans d'autres sets.\n\nPréparez-vous pour votre grande aventure, Insurgé !\n\nDragon's Dogma est un RPG action en solo à l'histoire riche, qui invite les joueurs à définir leur propre expérience, de l'apparence de leur Insurgé, à leur classe, leur groupe, la façon dont ils approchent les différentes situations, et plus encore. Avec cette suite tant attendue, le vaste monde de fantasy à explorer de Dragon's Dogma 2 vous tend désormais les bras.\n\nAu cours de votre voyage, des pions se joindront à vous. Ces mystérieux êtres surnaturels vous donneront l'impression d'être accompagné d'autres joueurs en chair et en os tout au long de cette aventure unique.\n\nL'expérience sera encore sublimée davantage par les systèmes physiques, l'intelligence artificielle (IA) et les graphismes à la pointe du progrès, qui donnent vie au monde de fantasy ensorcelant de Dragon's Dogma 2.\n\nDe l'action qui met votre créativité à l'épreuve\n\nFrappez à l'épée, tirez à l'arc et utilisez la magie.\nLes Classes de Dragon's Dogma 2 vous permettent d'aborder le combat comme vous l'entendez.",
            "sortie":"22 mars 2024",
            "image":["./assets/call-of-duty-modern-warfare-III-1.jpg","./assets/call-of-duty-modern-warfare-III-2.jpg","./assets/call-of-duty-modern-warfare-III-3.jpg"],
            "video":"",
            "prix":"87.38€",
            "Promo":"-21%",
            "genre":["jeux solo","action"]},
            {"id":24,
            "titre":"Palworld",
            "platform":["pc","xbox"],
            "description":"Ce jeu est toujours en cours de développement. Des modifications sont susceptibles d'être apportées d'ici sa sortie officielle. Veuillez noter que le jeu n'est pas encore terminé avant de procéder à son achat.\n\nQ. De quel genre de jeu s'agit-il ?\n\nTout dépend de si vous préférez vous la couler douce en compagnie des étranges créatures que sont les Pals, ou si vous entendez vous lancer dans une lutte à mort contre les braconniers.\n\nVous pouvez faire combattre les Pals, les faire se reproduire et ils pourront même vous aider dans votre travail aux champs ou encore à l'usine.\n\nVous pouvez aussi les vendre, les disséquer ou les manger.",
            "sortie":"19 janvier 2024",
            "image":["./assets/palworld-1.jpg","./assets/palworld-2.jpg","./assets/palworld-3.jpg"],
            "video":"",
            "prix":"23.99€",
            "Promo":"",
            "genre":["jeux solo","action","aventure","RPG"]},
            {"id":25,
            "titre":"EA Sports FC 24",
            "platform":["pc","ps5","xbox"],
            "description":"EA Sports FC 24 pour PC est un jeu de simulation de football, successeur des jeux FIFA, suite à la fin du partenariat avec la fédération internationale de football\n\nIl s'agit donc du premier jeu de la série, mais est en réalité le 31e jeu de la série.\n\nMalgré le changement de nom, la société a déclaré dans son communiqué que la franchise rebrandée garderait ses licences de plus de 19 000 joueurs, plus de 700 équipes, 100 stades, et plus de 30 langues - toutes basées sur de réelles personnes et équipes.",
            "sortie":"29 septembre 2023",
            "image":["./assets/ea-sports-fc-1.jpg","./assets/ea-sports-fc-2.jpg","./assets/ea-sports-fc-3.jpg"],
            "video":"",
            "prix":"25.91€",
            "Promo":"-63%",
            "genre":["jeux solo","sport"]},







        
        
    
] 